[[constraint]]
  version = "v1.6.0"
  name = "github.com/mattn/go-sqlite3"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "v3.3.2"

[[constraint]]
  name = "github.com/go-chi/render"
  version = "v1.0.0"

[[constraint]]
  name = "github.com/pressly/goose"
  version = "2.1.0"
